export const dndData = {
    razze: {
        'Dragonide': { str: 2, cha: 1, traits: "Scurovisione, Resistenza Draconica, Soffio Draconico" },
        'Elfo': { dex: 2, traits: "Scurovisione, Sensi Acuti, Retaggio Fatato, Trance" },
        'Umano': { str: 1, dex: 1, con: 1, int: 1, wis: 1, cha: 1, traits: "Versatilità Umana" },
        'Gnomo': { int: 2, traits: "Scurovisione, Resilienza Gnomica, Addestramento al Combattimento" },
        'Halfling': { dex: 2, traits: "Fortunato, Coraggioso, Agile" },
        'Mezzorco': { str: 2, con: 1, traits: "Scurovisione, Minaccioso, Tenacia Inesausta, Attacchi Selvaggi" },
        'Mezzelfo': { dex: 2, cha: 1, traits: "Scurovisione, Sensi Acuti, Retaggio Fatato, Trance" },
        'Nano': { con: 2, traits: "Scurovisione, Resilienza Nanica, Addestramento al Combattimento" },
        'Tiefling': { int: 1, cha: 2, traits: "Scurovisione, Resistenza al Fuoco, Retaggio Infernale" },
    },
    classi: {
            'Barbaro': { hitDice: 'd12', hpBase: 12, hpPerLevel: 7, saves: ['saveStr', 'saveCon'], fullCaster: false },
            'Bardo': { hitDice: 'd8', hpBase: 8, hpPerLevel: 5, saves: ['saveDex', 'saveCha'], fullCaster: true, spellAttribute: 'cha' },
            'Chierico': { hitDice: 'd8', hpBase: 8, hpPerLevel: 5, saves: ['saveWis', 'saveCha'], fullCaster: true, spellAttribute: 'wis' },
            'Druido': { hitDice: 'd8', hpBase: 8, hpPerLevel: 5, saves: ['saveInt', 'saveWis'], fullCaster: true, spellAttribute: 'wis' },
            'Guerriero': { hitDice: 'd10', hpBase: 10, hpPerLevel: 6, saves: ['saveStr', 'saveCon'], fullCaster: false },
            'Ladro': { hitDice: 'd8', hpBase: 8, hpPerLevel: 5, saves: ['saveDex', 'saveInt'], fullCaster: false },
            'Mago': { hitDice: 'd6', hpBase: 6, hpPerLevel: 4, saves: ['saveInt', 'saveWis'], fullCaster: true, spellAttribute: 'int' },
            'Monaco': { hitDice: 'd8', hpBase: 8, hpPerLevel: 5, saves: ['saveStr', 'saveDex'], fullCaster: false },
            'Paladino': { hitDice: 'd10', hpBase: 10, hpPerLevel: 6, saves: ['saveWis', 'saveCha'], fullCaster: false, spellAttribute: 'cha' },
            'Ranger': { hitDice: 'd10', hpBase: 10, hpPerLevel: 6, saves: ['saveStr', 'saveDex'], fullCaster: false, spellAttribute: 'wis' },
            'Stregone': { hitDice: 'd6', hpBase: 6, hpPerLevel: 4, saves: ['saveCon', 'saveCha'], fullCaster: true, spellAttribute: 'cha' },
            'Warlock': { hitDice: 'd8', hpBase: 8, hpPerLevel: 5, saves: ['saveWis', 'saveCha'], fullCaster: false, spellAttribute: 'cha' }
    },
    spellSlots: {
        1: [2], 
        2: [3], 
        3: [4, 2], 
        4: [4, 3], 
        5: [4, 3, 2],
        6: [4, 3, 3], 
        7: [4, 3, 3, 1], 
        8: [4, 3, 3, 2], 
        9: [4, 3, 3, 3, 1], 
        10: [4, 3, 3, 3, 2],
        11: [4, 3, 3, 3, 2, 1], 
        12: [4, 3, 3, 3, 2, 1], 
        13: [4, 3, 3, 3, 2, 1, 1],
        14: [4, 3, 3, 3, 2, 1, 1], 
        15: [4, 3, 3, 3, 2, 1, 1, 1], 
        16: [4, 3, 3, 3, 2, 1, 1, 1],
        17: [4, 3, 3, 3, 2, 1, 1, 1, 1], 
        18: [4, 3, 3, 3, 3, 1, 1, 1, 1],
        19: [4, 3, 3, 3, 3, 2, 1, 1, 1], 
        20: [4, 3, 3, 3, 3, 2, 2, 1, 1]
    }
};